// <auto-generated>
// This file is part of SortingApp. AssemblyInfo
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </auto-generated>


using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyDescription("This app sorts text in various formats.")]

// Remove or update the copyright as per your company's policy
[assembly: AssemblyCopyright("Copyright © RJRamirez 2025")]
[assembly: AssemblyTrademark("RJRamirez")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components. If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("92fb1cdf-9edd-4370-84d8-c694414a45a0")]
