// <auto-generated>
// This file contains the BubleSort class of SortingApp.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </auto-generated>


namespace SortingApp.Models
{
    /// <summary>
    /// Represents the BubbleSort algorithm.
    /// </summary>
    public class BubbleSort : ISortStrategy
    {
        /// <inheritdoc/>
        public string Sort(string input)
        {
            char[] array = input.ToCharArray();
            for (int i = 0; i < array.Length - 1; i++)
            {
                for (int j = 0; j < array.Length - i - 1; j++)
                {
                    if (array[j] > array[j + 1])
                    {
                        (array[j], array[j + 1]) = (array[j + 1], array[j]);
                    }
                }
            }
            return new string(array);
        }
    }

}
